util.py fixes
MideTechnology/ebmlite pull request #70
Opened 2021-05-22 20:52 UTC by pscheidler

Fixed an error when using util -p
Added --min option to util.py
Fixed propagation of 'ids' option in toXml

2021-05-24 16:16 UTC, StokesMIDE requested changes
This PR currently fails the unit tests.

2021-05-24 16:16 UTC, StokesMIDE commented on ebmlite/util.py
> +                           help="Generate minimal XML with ebml2xml. Just element nama and value")
typo

2021-05-24 16:16 UTC, StokesMIDE commented on ebmlite/util.py
> +            if 'b' in out.mode and out != sys.stdout:   # writexml wants to ooperate on a string, not binary output, file
typo

2021-05-24 16:16 UTC, StokesMIDE commented on ebmlite/util.py
>          root = toXml(doc)  # , offsets, sizes, types, ids)
Indentation? Attempting to run the script fails here.

2021-06-01 17:27 UTC, StokesMIDE commented
Thinking about it, users typically wouldn't want all that extra data, so omitting it would make more sense as the default. Maybe make the option `--max` instead? It's a minor change from what's there.

2021-06-01 19:44 UTC, pscheidler commented
> Thinking about it, users typically wouldn't want all that extra data, so omitting it would make more sense as the default. Maybe make the option `--max` instead? It's a minor change from what's there.

Personally, I'd rather go with a solution that already exists and is backwards compatible

2021-06-01 20:12 UTC, StokesMIDE commented
> Personally, I'd rather go with a solution that already exists and is backwards compatible

Yeah, I'm torn. Changing established behavior is generally something to avoid if possible, but on the other hand, the extra info is basically debugging stuff, and I'm not sure how many people would even notice if it were removed by default.

2021-06-01 20:23 UTC, StokesMIDE approved these changes
Looks good. 

It doesn't really change anything functionally, but ending with a newline is a PEP-8 recommendation. If you feel like adding it before merging, go for it; it won't affect my approval of the PR.

2021-06-01 21:06 UTC, StokesMIDE approved these changes

2021-06-02 15:10 UTC, closed without merging